[package]
name = "rust_exploit"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
memmap2 = "0.9"
byteorder = "1.4"
thiserror = "1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
bytes = "1.5"

[lib]
name = "rust_exploit"
crate-type = ["cdylib"]

[[bin]]
name = "heap_exploit"
path = "src/bin/heap_exploit.rs"
